### ISSUE TITLE
Review code

### ISSUE THREAD

**Issue by makara** [Wiredcraft/loopback-connector-couchbase3#2]
@dewey 

Can you help me review the code and share your thoughts?

Also it'd be cool if you can help on #1.

**Comment by dewey** [comment]
Hey @makara, thanks for the invite. I'm trying to get the project up and running right now so I can give proper feedback. I'll look into implementing the missing CRUD methods mentioned in #1 after that.

**Comment by dewey** [comment]
**initializeDataSource**

I'd use `localhost` as the default value instead of the hardcoded IP which could cause issues with certain setups if not overwritten in the `datasource.js`.

Other properties that we need:

- port
- password
- bucket
- connectionTimeout
- operationTimeout

**Couchbase.prototype.disconnect**

Maybe I'm misunderstanding something there but wouldn't it be easier to just use a simple if instead of promises there?

@makara Could we talk about this and #1 via Slack? I think someone needs to invite me to the channel, my Slack email is on my profile.

**Comment by makara** [comment]
Thanks @dewey .

> I'd use `localhost`

Please send me pull requests.

> Maybe I'm misunderstanding something there but wouldn't it be easier to just use a simple if instead of promises there?

I'm using promise here because connect() is using, and logically speaking it should happen after the connection is established, but in practice it could also be done before. If you can prove this with a test please send me a pull request.

**Comment by makara** [comment]
Hey @dewey .

You sent me a pull request but there's nothing about:

- `localhost`
- `disconnect()`
- CRUD

Can you re-fork and send me something about one or some of them?

**Comment by makara** [comment]
Thanks anyways. Closing.
